name: pounce

services:
  pounce:
    build: .
    container_name: pounce
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
